INSERT INTO "Currencies" (id, name, symbol)
VALUES
    ('USD', 'United States Dollar', '$'),
    ('EUR', 'Euro', '€'),
    ('JPY', 'Japanese Yen', '¥'),
    ('GBP', 'British Pound Sterling', '£'),
    ('AUD', 'Australian Dollar', 'A$'),
    ('CAD', 'Canadian Dollar', 'C$'),
    ('CHF', 'Swiss Franc', 'Fr'),
    ('CNY', 'Chinese Yuan', '¥'),
    ('SEK', 'Swedish Krona', 'kr'),
    ('NZD', 'New Zealand Dollar', 'NZ$'),
    ('MXN', 'Mexican Peso', '$'),
    ('SGD', 'Singapore Dollar', 'S$'),
    ('HKD', 'Hong Kong Dollar', 'HK$'),
    ('NOK', 'Norwegian Krone', 'kr'),
    ('KRW', 'South Korean Won', '₩'),
    ('TRY', 'Turkish Lira', '₺'),
    ('INR', 'Indian Rupee', '₹'),
    ('BRL', 'Brazilian Real', 'R$'),
    ('ZAR', 'South African Rand', 'R'),
    ('SAR', 'Saudi Riyal', '﷼'),
    ('AED', 'United Arab Emirates Dirham', 'د.إ'),
    ('IDR', 'Indonesian Rupiah', 'Rp'),
    ('PLN', 'Polish Złoty', 'zł'),
    ('THB', 'Thai Baht', '฿'),
    ('ILS', 'Israeli Shekel', '₪'),
    ('DKK', 'Danish Krone', 'kr'),
    ('MYR', 'Malaysian Ringgit', 'RM'),
    ('PHP', 'Philippine Peso', '₱'),
    ('CZK', 'Czech Koruna', 'Kč'),
    ('HUF', 'Hungarian Forint', 'Ft'),
    ('CLP', 'Chilean Peso', '$'),
    ('COP', 'Colombian Peso', '$'),
    ('ARS', 'Argentine Peso', '$'),
    ('RON', 'Romanian Leu', 'lei'),
    ('PEN', 'Peruvian Sol', 'S/'),
    ('BGN', 'Bulgarian Lev', 'лв'),
    ('KES', 'Kenyan Shilling', 'KSh'),
    ('EGP', 'Egyptian Pound', '£'),
    ('IQD', 'Iraqi Dinar', 'ع.د'),
    ('VND', 'Vietnamese Dong', '₫'),
    ('PKR', 'Pakistani Rupee', '₨'),
    ('UAH', 'Ukrainian Hryvnia', '₴'),
    ('MAD', 'Moroccan Dirham', 'د.م.'),
    ('RSD', 'Serbian Dinar', 'дин.'),
    ('DZD', 'Algerian Dinar', 'د.ج'),
    ('QAR', 'Qatari Riyal', '﷼'),
    ('LKR', 'Sri Lankan Rupee', '₨'),
    ('BHD', 'Bahraini Dinar', '.د.ب'),
    ('NPR', 'Nepalese Rupee', '₨');