name: PreMerge Checks

on:
    pull_request:
        branches: [dev, master]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.13.0'
            - name: Install
              run: npm install
            - name: Build
              run: |
                  npm run prebuild
                  npm run build
            - name: Lint
              run: npm run ci:lint
            - name: Format
              run: npm run ci:format
